version: "3.8"

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - classroom

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${APP_NAME}
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - classroom

networks:
  classroom:
    driver: bridge
