version: "3.8"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - classroom-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - classroom

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${APP_NAME}
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - classroom
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - classroom

volumes:
  classroom-db:
  mongodb_data:

networks:
  classroom:
    driver: bridge
