name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: classroom_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      RAILS_ENV: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: classroom_test
      POSTGRES_HOST: localhost
      MONGODB_URI: mongodb://mongodb:27017/classroom_test

    steps:     
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
